package uz.gita.budget_app.utils

import uz.gita.budget_app.R
import uz.gita.budget_app.data.models.CategoryModel

object AllCategoriesList {
    val list = listOf(
        CategoryModel("Baby", R.raw.baby),
        CategoryModel("Sea", R.raw.sea),
        CategoryModel("Bag", R.raw.bag),
        CategoryModel("Bird", R.raw.bird),
        CategoryModel("Birthday", R.raw.birthday),
        CategoryModel("Boat", R.raw.boat),
        CategoryModel("Books", R.raw.books),
        CategoryModel("Brain", R.raw.brain),
        CategoryModel("Building", R.raw.building),
        CategoryModel("Tennis", R.raw.tennis_ball),
        CategoryModel("Football", R.raw.football),
        CategoryModel("Cats", R.raw.cat),
        CategoryModel("Cars", R.raw.car),
        CategoryModel("Camera", R.raw.camera),
        CategoryModel("Chair", R.raw.chair),
        CategoryModel("Challenge", R.raw.challenge),
        CategoryModel("Clothes", R.raw.clothes),
        CategoryModel("Coffee", R.raw.coffee),
        CategoryModel("Coin", R.raw.coin),
        CategoryModel("coin_1", R.raw.coin_1),
        CategoryModel("Cup", R.raw.cup),
        CategoryModel("cycles", R.raw.cycles),
        CategoryModel("music", R.raw.music),
        CategoryModel("wc", R.raw.wc),
        CategoryModel("facemask", R.raw.facemask),
        CategoryModel("medican", R.raw.medican),
        CategoryModel("packages", R.raw.packages),
        CategoryModel("receipt", R.raw.receipt),
        CategoryModel("dinner", R.raw.dinner),
        CategoryModel("dog", R.raw.dog),
        CategoryModel("study", R.raw.study),
        CategoryModel("study_1", R.raw.study_1),
        CategoryModel("fun", R.raw.`fun`),
        CategoryModel("fix", R.raw.fix),
        CategoryModel("flower", R.raw.flower),
        CategoryModel("food", R.raw.food),
        CategoryModel("gift", R.raw.gift),
        CategoryModel("gas", R.raw.gas),
        CategoryModel("glass", R.raw.glass),
        CategoryModel("group_5", R.raw.group_5),
        CategoryModel("gym", R.raw.gym),
        CategoryModel("house", R.raw.house),
        CategoryModel("lawer", R.raw.lawer),
        CategoryModel("logo", R.raw.logo),
        CategoryModel("map", R.raw.map),
        CategoryModel("money", R.raw.money),
        CategoryModel("market", R.raw.market),
        CategoryModel("party", R.raw.party),
        CategoryModel("pie", R.raw.pie),
        CategoryModel("pill", R.raw.pill),
        CategoryModel("train", R.raw.train),
        CategoryModel("plane", R.raw.plane),
        CategoryModel("user", R.raw.user),
        CategoryModel("wallet", R.raw.wallet),
        CategoryModel("cook", R.raw.cook),
        CategoryModel("run", R.raw.run),
        CategoryModel("shower", R.raw.shower),
        CategoryModel("store", R.raw.store),
    )
}